%% CarasLabDB — usage walkthrough
% Demonstrates connecting to the lab metadata database and exercising the
% main insert / retrieve / supersede paths. This is a script for reading and
% adapting, not an automated test — it assumes a reachable database whose
% schema was created from design_docs/schema.sql.
%
% Put the parent of the @CarasLabDB folder on your path:
%     addpath("C:\src\CarasLabDB");

%% Connect (native postgresql interface; requires Database Toolbox)
% The current person is resolved by email and used for created_by /
% recorded_by on every insert below.
db = CarasLabDB( ...
    Username      = "lab_rw", ...
    Password      = "change-me", ...
    Server        = "nas-main.lab", ...
    Port          = 5432, ...
    DatabaseName  = "lab", ...
    PersonEmail   = "dstolz@umd.edu");

assert(db.isOpen())

%% Seed a person if needed, then point the object at them
% (Skip if the person already exists — email is UNIQUE.)
% pid = db.addPerson(FullName="Daniel Stolzberg", Email="dstolz@umd.edu", Role="PI");
% db.setPerson(PersonEmail="dstolz@umd.edu");

%% Reference / lookup rows
rootId = db.addStorageRoot(Name="nas-main", Description="primary NAS");
db.addProbe(Manufacturer="Cambridge NeuroTech", Model="H6", NChannels=64, ...
    Geometry=struct("layout", "linear", "pitch_um", 20));

%% A project (unique name), its members, and a project-level document
% Every subject must belong to a project, so create one first.
projId = db.addProject( ...
    Name        = "Gerbil AC plasticity", ...
    Description = "Auditory cortex plasticity in Mongolian gerbils", ...
    StartedOn   = datetime(2026, 1, 1));

% Associate one or more people with the project (many-to-many).
db.addProjectMember(ProjectId=projId, PersonId=db.CurrentPersonId, Role="PI");

% Attach project documents: NAS files and external links (Google Docs/Sheets).
db.addProjectArtifact(ProjectId=projId, Title="Grant aims", ...
    Kind="google_doc", Uri="https://docs.google.com/document/d/abc123/edit");
db.addProjectArtifact(ProjectId=projId, Title="Animal roster", ...
    Kind="google_sheet", Uri="https://docs.google.com/spreadsheets/d/def456/edit");
db.addProjectArtifact(ProjectId=projId, Title="Surgery protocol", ...
    Kind="file", ContentType="pdf", ...
    StorageRootId=rootId, RelativePath="projects/gerbil-ac/protocol.pdf");

%% A subject (associated with the project) and a session
db.addSubject( ...
    SubjectId    = "G-0421", ...
    ProjectId    = projId, ...
    SpeciesCode  = "meriones_unguiculatus", ...
    Sex          = "M", ...
    DateOfBirth  = datetime(2026, 1, 15));

sid = db.addSession( ...
    SubjectId     = "G-0421", ...
    Label         = "2026-07-02_pen1", ...
    StorageRootId = rootId, ...
    RelativePath  = "G-0421/2026-07-02_pen1", ...
    StartedAt     = datetime("now", "TimeZone", "local"), ...
    Rig           = "rig-A");

%% A recording event (must reference a session) + its raw artifact
eid = db.addRecordingEvent( ...
    SubjectId             = "G-0421", ...
    SessionId             = sid, ...
    OccurredAt            = datetime("now", "TimeZone", "local"), ...
    AcquisitionSystemCode = "intan_rhx", ...
    SampleRateHz          = 30000, ...
    NChannels             = 64, ...
    DurationS             = 1800, ...
    HardwareConfig        = struct("gain", 200, "reference", "common_median"));

rawId = db.addArtifact( ...
    ProducedByEventId = eid, ...
    StorageRootId     = rootId, ...
    SubjectId         = "G-0421", ...
    SessionId         = sid, ...
    RelativePath      = "G-0421/2026-07-02_pen1/raw.dat", ...
    Checksum          = "ab12cd34ef56", ...
    ChecksumAlgo      = "sha256", ...
    SizeBytes         = 1.2e10, ...
    Role              = "raw", ...
    Format            = "dat");

%% An analysis run that consumes the raw file and produces spikes
anId = db.addAnalysisEvent( ...
    SubjectId    = "G-0421", ...
    SessionId    = sid, ...
    OccurredAt   = datetime("now", "TimeZone", "local"), ...
    PipelineName = "kilosort4", ...
    CodeVersion  = "v4.0.1", ...
    Parameters   = struct("Th", [9 3], "nblocks", 5), ...
    Status       = "succeeded");

db.addEventInput(EventId=anId, ArtifactId=rawId, Role="raw");   % consumes

spikesId = db.addArtifact( ...
    ProducedByEventId = anId, ...
    StorageRootId     = rootId, ...
    SubjectId         = "G-0421", ...
    SessionId         = sid, ...
    RelativePath      = "G-0421/2026-07-02_pen1/spikes.npy", ...
    Checksum          = "99aa88bb", ...
    Role              = "spikes", ...
    Format            = "npy");

%% Retrieval (defaults to the *_active views)
projects  = db.getProjects(Name="Gerbil AC plasticity");
members   = db.getProjectMembers(ProjectId=projId);
projDocs  = db.getProjectArtifacts(ProjectId=projId);
subjects  = db.getSubjects(ProjectId=projId);
events    = db.getEvents(SubjectId="G-0421");
artifacts = db.getArtifacts(SessionId=sid);
current   = db.getSubjectCurrent(SubjectId="G-0421");
disp(projects); disp(members); disp(projDocs);
disp(subjects); disp(events); disp(artifacts); disp(current);

% Full provenance ancestry of the spikes file.
lineage = db.artifactLineage(spikesId, Direction="up");
disp(lineage);

%% Correction via supersede (append-only: no UPDATE/DELETE)
% Log a weight, then correct it. The old husbandry row disappears from
% event_active; the new one carries supersedes -> old.
wEid = db.addHusbandryEvent( ...
    SubjectId  = "G-0421", ...
    OccurredAt = datetime("now", "TimeZone", "local"), ...
    Measure    = "weight", ...
    WeightG    = 72.4);

newWEid = db.supersedeEvent(wEid, ...
    DetailOverrides = struct("weight_g", 71.9), ...
    Notes           = "scale recalibrated");
fprintf("weight event %s superseded by %s\n", wEid, newWEid);

%% Ad-hoc SQL escape hatch
n = db.runQuery("SELECT count(*) AS n FROM lab.event_active;");
fprintf("active events: %d\n", n.n(1));

%% Done
delete(db);   % closes the connection (since this object opened it)
