function specs = eventFieldSpecs(eventType)
%EVENTFIELDSPECS Field descriptors for a given event type's detail table.
%
%   specs = CarasLabDBApp.eventFieldSpecs(eventType) returns a struct array
%   describing the type-specific detail fields for one of the eight event
%   types. It is the single source that drives the dynamic add/supersede form
%   and mirrors the detail tables in design_docs/schema.sql.
%
%   Each element has:
%       Key    - form field key (matches Arg, used internally)
%       Arg    - Name=Value argument name on the matching add*Event method
%       Col    - database column name (used for supersede DetailOverrides)
%       Label  - human label shown in the form
%       Type   - "text" | "textarea" | "number" | "enum" | "bool" | "datetime"
%       Choices- allowed values for Type=="enum" (else strings(1,0))
%
%   Nullable boolean columns are described as an enum of "true"/"false" rather
%   than "bool": a checkbox has no third state, so it cannot express NULL and
%   would write false into a column the user never touched.
%
%   See also CARASLABDBAPP, CARASLABDBAPP/SHOWEVENTEDITOR.

    arguments
        eventType (1,1) string
    end

    switch eventType
        case "birth"
            specs = [ ...
                local_f("DamSubjectId","dam_subject_id","Dam subject id","text"), ...
                local_f("SireSubjectId","sire_subject_id","Sire subject id","text"), ...
                local_f("LitterId","litter_id","Litter id","text"), ...
                local_f("BirthWeightG","birth_weight_g","Birth weight (g)","number")];

        case "surgery"
            specs = [ ...
                local_f("Procedure","procedure","Procedure","text"), ...
                local_f("SurgeonId","surgeon_id","Surgeon (person id)","text"), ...
                local_f("Anesthesia","anesthesia","Anesthesia","text"), ...
                local_f("TargetRegion","target_region","Target region","text"), ...
                local_e("Hemisphere","hemisphere","Hemisphere",["L","R","bilateral"]), ...
                local_f("StereotaxApMm","stereotax_ap_mm","Stereotax AP (mm)","number"), ...
                local_f("StereotaxMlMm","stereotax_ml_mm","Stereotax ML (mm)","number"), ...
                local_f("StereotaxDvMm","stereotax_dv_mm","Stereotax DV (mm)","number"), ...
                local_f("ProbeId","probe_id","Probe id","text"), ...
                local_f("Outcome","outcome","Outcome","text")];

        case "recording"
            specs = [ ...
                local_f("AcquisitionSystemCode","acquisition_system_code","Acquisition system","text"), ...
                local_f("ProbeId","probe_id","Probe id","text"), ...
                local_e("Modality","modality","Modality",["ephys","video","behavior","multimodal"]), ...
                local_f("SampleRateHz","sample_rate_hz","Sample rate (Hz)","number"), ...
                local_f("NChannels","n_channels","Channels","number"), ...
                local_f("DurationS","duration_s","Duration (s)","number"), ...
                local_f("StimulusProtocol","stimulus_protocol","Stimulus protocol","text"), ...
                local_f("HardwareConfig","hardware_config","Hardware config (JSON)","textarea")];

        case "behavior"
            specs = [ ...
                local_f("Task","task","Task","text"), ...
                local_f("Paradigm","paradigm","Paradigm","text"), ...
                local_f("Stage","stage","Stage","text"), ...
                local_f("TrialsCompleted","trials_completed","Trials completed","number"), ...
                local_f("Performance","performance","Performance","number"), ...
                local_f("Reward","reward","Reward","text")];

        case "husbandry"
            specs = [ ...
                local_f("Measure","measure","Measure (required)","text"), ...
                local_f("WeightG","weight_g","Weight (g)","number"), ...
                local_f("WaterMl","water_ml","Water (mL)","number"), ...
                local_f("HealthStatus","health_status","Health status","text")];

        case "endpoint"
            specs = [ ...
                local_f("Method","method","Method","text"), ...
                local_f("PerfusionFixative","perfusion_fixative","Perfusion fixative","text"), ...
                local_e("TissueCollected","tissue_collected","Tissue collected", ...
                        ["true","false"]), ...
                local_f("Disposition","disposition","Disposition","text")];

        case "histology"
            specs = [ ...
                local_f("Technique","technique","Technique","text"), ...
                local_f("TargetRegion","target_region","Target region","text"), ...
                local_f("Stain","stain","Stain","text"), ...
                local_f("Microscope","microscope","Microscope","text")];

        case "analysis"
            specs = [ ...
                local_f("PipelineId","pipeline_id","Pipeline id","text"), ...
                local_f("PipelineName","pipeline_name","Pipeline name","text"), ...
                local_f("CodeVersion","code_version","Code version","text"), ...
                local_f("Parameters","parameters","Parameters (JSON)","textarea"), ...
                local_f("Environment","environment","Environment (JSON)","textarea"), ...
                local_dt("StartedAt","started_at","Started at"), ...
                local_dt("FinishedAt","finished_at","Finished at"), ...
                local_e("Status","status","Status",["running","succeeded","failed"])];

        otherwise
            error("CarasLabDBApp:unknownEventType", ...
                "Unknown event type '%s'.", eventType);
    end
end

% ---- local spec constructors -------------------------------------------------

function s = local_f(arg, col, label, type)
    s = struct("Key", string(arg), "Arg", string(arg), "Col", string(col), ...
        "Label", string(label), "Type", string(type), "Choices", strings(1,0));
end

function s = local_e(arg, col, label, choices)
    s = local_f(arg, col, label, "enum");
    s.Choices = string(choices);
end

function s = local_dt(arg, col, label)
    s = local_f(arg, col, label, "datetime");
end
